- name: Install MySQL Server
  ansible.builtin.dnf:
    name:
      - mysql-community-server
    state: present
  ignore_errors: yes
  register: mysql_community_install

- name: Fallback - Install MariaDB if MySQL community not available
  ansible.builtin.dnf:
    name: mariadb-server
    state: present
  when: mysql_community_install is failed

- name: Start MySQL/MariaDB service
  ansible.builtin.systemd_service:
    state: restarted
    name: "{{ 'mysqld' if mysql_community_install is succeeded else 'mariadb' }}"
    enabled: true

- name: Ensure Root Password is Set
  ansible.builtin.shell: |
    mysql -uroot -p{{ mysql_root_password }} -e "QUIT" || \
    mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
  args:
    executable: /bin/bash
  register: root_pass_setup
  failed_when: false

- name: Allow Remote Connections
  ansible.builtin.lineinfile:
    path: /etc/my.cnf.d/mysql-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    create: yes
  notify: Restart MySQL

- name: Create Roboshop User
  ansible.builtin.shell: |
    mysql -uroot -p{{ mysql_root_password }} <<EOF
    CREATE USER IF NOT EXISTS 'roboshop'@'%' IDENTIFIED WITH mysql_native_password BY 'RoboShop@1';
    GRANT ALL PRIVILEGES ON *.* TO 'roboshop'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
    EOF
  args:
    executable: /bin/bash