---
- name: Import Node JS
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
  vars:
    component: catalogue

# ---------------- REPOSITORY SETUP ----------------
- name: Copy MongoDB repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Shell (mongosh)
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

# ---------------- MongoDB DATA INITIALIZATION ----------------
- name: Check if catalogue data already exists
  ansible.builtin.shell: >
    mongosh --host mongodb-{{ env }}.kiranpanchavati.online
    --quiet --eval "db.getSiblingDB('catalogue').products.countDocuments()"
  register: catalogue_count
  changed_when: false
  failed_when: false

- name: Debug catalogue count
  ansible.builtin.debug:
    var: catalogue_count.stdout

- name: Load catalogue master data
  ansible.builtin.shell: >
    mongosh --host mongodb-{{ env }}.kiranpanchavati.online
    < /app/db/master-data.js
  when:
    - catalogue_count.stdout | default('0') | int == 0

# ---------------- SYSTEMD ----------------
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable and start catalogue service
  ansible.builtin.systemd_service:
    name: catalogue
    enabled: true
    state: restarted

# ---------------- VALIDATION ----------------
# ---------------- VALIDATION ----------------
- name: Verify catalogue service is running
  ansible.builtin.command:
    cmd: systemctl is-active catalogue
  register: catalogue_is_active
  changed_when: false
  failed_when:
    - catalogue_is_active.stdout != "active"