####################################################################
# 2. Create roboshop user
####################################################################
- name: Create roboshop user
  ansible.builtin.user:
    name: roboshop
    create_home: yes

####################################################################
# 3. Copy systemd service file
####################################################################
- name: Copy {{component}} systemd service file
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

####################################################################
# 4. Remove old app directory
####################################################################
- name: Remove old /app directory
  ansible.builtin.file:
    path: /app
    state: absent

####################################################################
# 5. Create /app directory
####################################################################
- name: Create /app directory
  ansible.builtin.file:
    path: /app
    state: directory
    owner: roboshop
    group: roboshop

####################################################################
# 6. Download application code
####################################################################
- name: Download {{component}} application code
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip"
    dest: "/tmp/{{component}}.zip"

####################################################################
# 7. Extract application code
####################################################################
- name: Extract {{component}} application code
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes
    owner: roboshop
    group: roboshop